//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkemy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_User_Info
    {
        public int IdUs { get; set; }
        public string UsernameUs { get; set; }
        public string PasswordUs { get; set; }
        public string C_Roles { get; set; }
    }
}
